services:
  postgres:
    image: postgres:16-alpine
    container_name: urunankita_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: urunankita
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - urunankita_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d urunankita"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  urunankita_pgdata:
    driver: local
